spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

keycloak:
  hostname: keycloak.local
  theme: genericempresa
  realm-file: classpath:realm-config/realm-ecosistema.json

